-- highlight support for common plugins, including:
-- * nvim-tree
-- * cmp
-- * GitSigns
-- * Telescope
-- * Mini.pick

local function _set()
  local c = require("colors.darkmatter")
  local conf = c.get_conf()

  c.hl_with_defaults("NvimTreeNormal", c.localtheme.fg_dim, c.palette.neotreebg)
  c.hl_with_defaults("NvimTreeEndOfBuffer", c.localtheme.bg_dim, c.palette.neotreebg)
  c.hl_with_defaults("NvimTreeVertSplit", c.localtheme.bg0, c.localtheme.bg0)
  c.link("NvimTreeSymlinkFolderName", "Blue")
  c.link("NvimTreeSymlinkFolderIcon", "BlueBold")
  c.link("NvimTreeFolderName", "Green")
  c.link("NvimTreeRootFolder", "Darkyellow")
  c.link("NvimTreeFolderIcon", "GreenBold")
  c.link("NeoTreeDirectoryIcon", "GreenBold")
  c.link("NeoTreeDirectoryName", "GreenBold")

  c.link("NvimTreeEmptyFolderName", "Fg")
  c.link("NvimTreeOpenedFolderName", "GreenBold")
  c.link("NvimTreeExecFile", "Fg")
  c.link("NvimTreeOpenedFile", "Orange")
  c.link("NvimTreeSpecialFile", "Fg")
  c.link("NvimTreeImageFile", "Fg")
  c.link("NvimTreeMarkdownFile", "Fg")
  c.link("NvimTreeIndentMarker", "SymbolsOutlineConnector")
  c.link("NvimTreeFolderArrowOpen", "SymbolsOutlineConnector")
  c.link("NvimTreeFolderArrowClosed", "SymbolsOutlineConnector")
  c.link("NvimTreeGitDirty", "Yellow")
  c.link("NvimTreeGitStaged", "Blue")
  c.link("NvimTreeGitMerge", "Orange")
  c.link("NvimTreeGitRenamed", "Purple")
  c.link("NvimTreeGitNew", "Green")
  c.link("NvimTreeGitDeleted", "Red")
  c.link("NvimTreeLspDiagnosticsError", "RedSign")
  c.link("NvimTreeLspDiagnosticsWarning", "YellowSign")
  c.link("NvimTreeLspDiagnosticsInformation", "BlueSign")
  c.link("NvimTreeLspDiagnosticsHint", "GreenSign")
  c.link("NvimTreeCursorLine", "TreeCursorLine")

  c.link("NeoTreeFilenameOpened", "OrangeBold")
   -- CMP (with custom menu setup)
  c.link("CmpItemMenu", "Fg")
  c.link("CmpItemMenuDetail", "Debug")
  c.link("CmpItemMenuBuffer", "FgDim")
  c.link("CmpItemMenuSnippet", "Number")
  c.link("CmpItemMenuLSP", "StorageClass")
  c.link("CmpItemAbbr", "Fg")
  c.set_hl(0, "CmpItemAbbrDeprecated", { bg = "NONE", strikethrough = true, fg = "#808080" })
  c.link("CmpItemAbbrMatch", "RedBold")
  c.link("CmpItemAbbrMatchFuzzy", "DarkPurpleBold")
  c.hl_with_defaults("CmpPmenu", c.localtheme.fg, c.localtheme.bg_dim)
  c.hl_with_defaults("CmpPmenuBorder", c.palette.grey_dim, c.localtheme.bg_dim)
  c.hl_with_defaults("CmpGhostText", c.palette.grey, c.palette.none)
  c.link("CmpItemKindDefault", "FgDim")
  c.link("CmpItemKind", "CmpItemKindDefault")
  c.link("CmpItemMenuPath", "CmpItemMenu")
  c.link("CmpItemKindStruct", "Structure")
  c.link("CmpItemKindConstructor", "@constructor")
  c.link("CmpItemKindMethod", "Method")
  c.link("CmpItemKindModule", "@include")
  c.link("CmpItemKindClass", "Class")
  c.link("CmpItemKindVariable", "Fg")
  c.link("CmpItemKindProperty", "Member")
  c.link("CmpItemKindField", "Member")
  c.link("CmpItemKindFunction", "Function")
  c.link("CmpItemKindKeyword", "Keyword")
  c.link("CmpItemKindText", "Fg")
  c.link("CmpItemKindUnit", "@include")
  c.link("CmpItemKindConstant", "Constant")
  c.link("CmpItemKindEnum", "Constant")
  c.link("CmpItemKindSnippet", "CmpItemMenuSnippet")
  c.link("CmpItemKindOperator", "Operator")
  c.link("CmpItemKindInterface", "Interface")
  c.link("CmpItemKindValue", "StorageClass")
  c.hl_with_defaults("CmpFloat", c.localtheme.fg_dim, c.palette.neotreebg)
  c.hl_with_defaults("CmpBorder", c.localtheme.bg4, c.palette.neotreebg)

  c.hl_with_defaults("TelescopeBorder", c.localtheme.accent, c.palette.neotreebg)
  c.hl_with_defaults("TelescopePromptBorder", c.localtheme.accent, c.palette.neotreebg)
  c.hl_with_defaults("TelescopeNormal", c.localtheme.fg_dim, c.palette.neotreebg)
  c.hl("TelescopeTitle", c.localtheme.accent_fg, c.localtheme.accent, conf.attrib.bold)
  c.hl("TelescopePromptNormal", c.localtheme.fg_dim, c.palette.neotreebg, conf.attrib.bold)
  c.hl("TelescopeMatching", c.palette.deepred, c.palette.none, conf.attrib.bold)

  c.link("MiniPickBorder", "TelescopeBorder")
  c.link("MiniPickBorderBusy", "TelescopeBorder")
  c.link("MiniPickBorderText", "TelescopeBorder")
  c.link("MiniPickNormal", "TelescopeNormal")
  c.link("MiniPickHeader", "TelescopeTitle")
  c.link("MiniPickMatchCurrent", "Visual")
  c.link("TelescopeResultsLineNr", "Yellow")
  c.link("TelescopePromptPrefix", "Blue")
  c.link("TelescopeSelection", "TreeCursorLine")
  c.link("FzfLuaNormal", "TelescopeNormal")
  c.link("FzfLuaBorder", "TelescopeBorder")
  c.link("FzfLuaSearch", "TelescopeMatching")

  c.link("GitSignsAdd", "GreenSign")
  c.link("GitSignsAddNr", "GreenSign")
  c.link("GitSignsChange", "BlueSign")
  c.link("GitSignsChangeNr", "BlueSign")
  c.link("GitSignsDelete", "RedSign")
  c.link("GitSignsDeleteNr", "RedSign")
  c.link("GitSignsAddLn", "GreenSign")
  c.link("GitSignsChangeLn", "BlueSign")
  c.link("GitSignsDeleteLn", "RedSign")
  c.link("GitSignsCurrentLineBlame", "Grey")
  c.link("GitSignsAddInline", "Visual")
  c.link("GitSignsChangeInline", "Visual")
  c.link("GitSignsDeleteInline", "Visual")

  c.link("TroubleNormal", "NeoTreeNormalNC")
end

local M = {}
function M.set()
  _set()
end

return M

