-- highlight support for common plugins, including:
-- * nvim-tree
-- * cmp
-- * GitSigns
-- * Telescope
-- * Mini.pick

-- TODO: CMP needs colorscheme harmonization
local c = require("colors.darkmatter")
local conf = c.get_conf()

c.hl_with_defaults("NvimTreeNormal", c.localtheme.fg, c.palette.neotreebg)
c.hl_with_defaults("NvimTreeEndOfBuffer", c.localtheme.bg_dim, c.palette.neotreebg)
c.hl_with_defaults("NvimTreeVertSplit", c.localtheme.bg0, c.localtheme.bg0)
c.link("NvimTreeSymlinkFolderName", "Blue")
c.link("NvimTreeSymlinkFolderIcon", "BlueBold")
c.link("NvimTreeFolderName", "Green")
c.link("NvimTreeRootFolder", "Darkyellow")
c.link("NvimTreeFolderIcon", "GreenBold")
c.link("NvimTreeEmptyFolderName", "Fg")
c.link("NvimTreeOpenedFolderName", "GreenBold")
c.link("NvimTreeExecFile", "Fg")
c.link("NvimTreeOpenedFile", "PurpleBold")
c.link("NvimTreeSpecialFile", "Fg")
c.link("NvimTreeImageFile", "Fg")
c.link("NvimTreeMarkdownFile", "Fg")
c.link("NvimTreeIndentMarker", "SymbolsOutlineConnector")
c.link("NvimTreeFolderArrowOpen", "SymbolsOutlineConnector")
c.link("NvimTreeFolderArrowClosed", "SymbolsOutlineConnector")
c.link("NvimTreeGitDirty", "Yellow")
c.link("NvimTreeGitStaged", "Blue")
c.link("NvimTreeGitMerge", "Orange")
c.link("NvimTreeGitRenamed", "Purple")
c.link("NvimTreeGitNew", "Green")
c.link("NvimTreeGitDeleted", "Red")
c.link("NvimTreeLspDiagnosticsError", "RedSign")
c.link("NvimTreeLspDiagnosticsWarning", "YellowSign")
c.link("NvimTreeLspDiagnosticsInformation", "BlueSign")
c.link("NvimTreeLspDiagnosticsHint", "GreenSign")
c.link("NvimTreeCursorLine", "TreeCursorLine")

 -- CMP (with custom menu setup)
c.set_hl(0, "CmpItemKindDefault", { fg = "#cc5de8" })
c.set_hl(0, "CmpItemMenu", { fg = "#ededcf" })
c.set_hl(0, "CmpItemMenuDetail", { fg = "#ffe066" })
c.set_hl(0, "CmpItemMenuBuffer", { fg = "#898989" })
c.set_hl(0, "CmpItemMenuSnippet", { fg = "#cc5de8" })
c.set_hl(0, "CmpItemMenuLSP", { fg = "#cfa050" })
c.set_hl(0, "CmpItemAbbr", { fg = "#d0b1d0" })
c.set_hl(0, "CmpItemAbbrDeprecated", { bg = "NONE", strikethrough = true, fg = "#808080" })
c.set_hl(0, "mpItemAbbrMatch", { bg = "NONE", fg = "#f03e3e", bold = true })
c.set_hl(0, "CmpItemAbbrMatchFuzzy", { bg = "NONE", fg = "#fd7e14", bold = true })
c.set_hl(0, "CmpItemKindModule", { bg = "NONE", fg = "#FF7F50" })
c.set_hl(0, "CmpItemKindClass", { bg = "none", fg = "#FFAF00" })
c.set_hl(0, "CmpItemKindVariable", { bg = "none", fg = "#9CDCFE" })
c.set_hl(0, "CmpItemKindProperty", { bg = "none", fg = "#9CDCFE" })
c.set_hl(0, "CmpItemKindFunction", { bg = "none", fg = "#C586C0" })
c.set_hl(0, "CmpItemKindKeyword", { bg = "none", fg = "#FF5FFF" })
c.set_hl(0, "CmpItemKindText", { bg = "none", fg = "#D4D4D4" })
c.set_hl(0, "CmpItemKindUnit", { bg = "none", fg = "#D4D4D4" })
c.set_hl(0, "CmpItemKindConstant", { bg = "none", fg = "#409F31" })
c.set_hl(0, "CmpItemKindSnippet", { bg = "none", fg = "#E3E300" })
c.hl_with_defaults("CmpPmenu", c.localtheme.fg, c.localtheme.bg_dim)
c.hl_with_defaults("CmpPmenuBorder", c.palette.grey_dim, c.localtheme.bg_dim)
c.hl_with_defaults("CmpGhostText", c.palette.grey, c.palette.none)
c.link("CmpItemKind", "CmpItemKindDefault")
c.link("CmpItemMenuPath", "CmpItemMenu")
c.link("CmpItemKindStruct", "CmpItemKindClass")
c.link("CmpItemKindConstructor", "CmpItemKindFunction")
c.link("CmpItemKindMethod", "CmpItemKindFunction")

c.hl_with_defaults("TelescopeBorder", c.localtheme.accent, c.localtheme.bg_dim)
c.hl_with_defaults("TelescopePromptBorder", c.localtheme.accent, c.localtheme.bg_dim)
c.hl_with_defaults("TelescopeNormal", c.localtheme.fg_dim, c.localtheme.bg_dim)
c.hl("TelescopeTitle", c.localtheme.accent_fg, c.localtheme.accent, conf.attrib.bold)
c.hl("TelescopePromptNormal", c.localtheme.fg_dim, c.localtheme.bg_dim, conf.attrib.bold)
c.hl("TelescopeMatching", c.palette.deepred, c.palette.none, conf.attrib.bold)

c.link("MiniPickBorder", "TelescopeBorder")
c.link("MiniPickBorderBusy", "TelescopeBorder")
c.link("MiniPickBorderText", "TelescopeBorder")
c.link("MiniPickNormal", "TelescopeNormal")
c.link("MiniPickHeader", "TelescopeTitle")
c.link("MiniPickMatchCurrent", "Visual")
c.link("TelescopeResultsLineNr", "Yellow")
c.link("TelescopePromptPrefix", "Blue")
c.link("TelescopeSelection", "TreeCursorLine")
c.link("FzfLuaNormal", "TelescopeNormal")
c.link("FzfLuaBorder", "TelescopeBorder")
c.link("FzfLuaSearch", "TelescopeMatching")

c.link("GitSignsAdd", "GreenSign")
c.link("GitSignsAddNr", "GreenSign")
c.link("GitSignsChange", "BlueSign")
c.link("GitSignsChangeNr", "BlueSign")
c.link("GitSignsDelete", "RedSign")
c.link("GitSignsDeleteNr", "RedSign")
c.link("GitSignsAddLn", "GreenSign")
c.link("GitSignsChangeLn", "BlueSign")
c.link("GitSignsDeleteLn", "RedSign")
c.link("GitSignsCurrentLineBlame", "Grey")
c.link("GitSignsAddInline", "Visual")
c.link("GitSignsChangeInline", "Visual")
c.link("GitSignsDeleteInline", "Visual")

c.link("TroubleNormal", "NeoTreeNormalNC")

