local c = require("colors.darkmatter")
local conf = c.get_conf()

c.hl("markdownH1", c.localtheme.red, c.palette.none, conf.attrib.bold)
c.hl("markdownH2", c.localtheme.orange, c.palette.none, conf.attrib.bold)
c.hl("markdownH3", c.localtheme.yellow, c.palette.none, conf.attrib.bold)
c.hl("markdownH4", c.localtheme.green, c.palette.none, conf.attrib.bold)
c.hl("markdownH5", c.localtheme.blue, c.palette.none, conf.attrib.bold)
c.hl("markdownH6", c.palette.purple, c.palette.none, conf.attrib.bold)
c.hl("markdownUrl", c.localtheme.blue, c.palette.none, { underline = true })
c.hl("markdownItalic", c.palette.none, c.palette.none, conf.attrib.italic)
c.hl("markdownBold", c.palette.none, c.palette.none, conf.attrib.bold)
c.hl("markdownItalicDelimiter", c.palette.grey, c.palette.none, conf.attrib.italic)
c.link("markdownCode", "Purple")
c.link("markdownCodeBlock", "Green")
c.link("markdownCodeDelimiter", "Green")
c.link("markdownBlockquote", "Grey")
c.link("markdownListMarker", "Red")
c.link("markdownOrderedListMarker", "Red")
c.link("markdownRule", "Purple")
c.link("markdownHeadingRule", "Grey")
c.link("markdownUrlDelimiter", "Grey")
c.link("markdownLinkDelimiter", "Grey")
c.link("markdownLinkTextDelimiter", "Grey")
c.link("markdownHeadingDelimiter", "Grey")
c.link("markdownLinkText", "Red")
c.link("markdownUrlTitleDelimiter", "Green")
c.link("markdownIdDeclaration", "markdownLinkText")
c.link("markdownBoldDelimiter", "Grey")
c.link("markdownId", "Yellow")
c.hl("mdURL", c.localtheme.blue, c.palette.none, { underline = true })
c.hl("mkdInineURL", c.localtheme.blue, c.palette.none, { underline = true })
c.hl("mkdItalic", c.palette.grey, c.palette.none, conf.attrib.italic)
c.link("mkdCodeDelimiter", "Green")
c.link("mkdBold", "Grey")
c.hl("mkdLink", c.localtheme.blue, c.palette.none, { underline = true })
c.link("mkdHeading", "Grey")
c.link("mkdListItem", "Red")
c.link("mkdRule", "Purple")
c.link("mkdDelimiter", "Grey")
c.link("mkdId", "Yellow")
c.link("texStatement", "BlueItalic")
c.link("texOnlyMath", "Grey")
c.link("texDefName", "Yellow")
c.link("texNewCmd", "Orange")
c.link("texCmdName", "BlueBold")
c.link("texBeginEnd", "Red")
c.link("texBeginEndName", "Green")
c.link("texDocType", "Type")
c.link("texDocZone", "BlueBold")
c.link("texDocTypeArgs", "Orange")
c.link("texInputFile", "Green")
c.link("texFileArg", "Green")
c.link("texCmd", "BlueItalic")
c.link("texCmdPackage", "BlueItalic")
c.link("texCmdDef", "Red")
c.link("texDefArgName", "Yellow")
c.link("texCmdNewcmd", "Red")
c.link("texCmdClass", "Red")
c.link("texCmdTitle", "Red")
c.link("texCmdAuthor", "Red")
c.link("texCmdEnv", "Red")
c.link("texCmdPart", "BlueBold")
c.link("texEnvArgName", "Green")

