local function _set()
  local c = require("darkmatter")
  local conf = c.get_conf()

  c.link("markdownH1", "htmlH1")
  c.link("@markup.heading.1.markdown", "htmlH1")
  c.link("markdownH2", "htmlH2")
  c.link("@markup.heading.2.markdown", "htmlH2")
  c.link("markdownH3", "htmlH3")
  c.link("@markup.heading.3.markdown", "htmlH3")
  c.link("markdownH4", "htmlH4")
  c.link("@markup.heading.4.markdown", "htmlH4")
  c.link("markdownH5", "htmlH5")
  c.link("@markup.heading.5.markdown", "htmlH5")
  c.link("markdownH6", "htmlH6")
  c.link("@markup.heading.6.markdown", "htmlH6")
  c.hl("markdownUrl", c.P.blue, c.NONE, { underline = true })
  c.hl("markdownItalic", c.NONE, c.NONE, conf.attrib.italic)
  c.hl("markdownBold", c.NONE, c.NONE, conf.attrib.bold)
  c.hl("markdownItalicDelimiter", c.P.grey, c.NONE, conf.attrib.italic)
  c.link("markdownCode", "Purple")
  c.link("markdownCodeBlock", "Green")
  c.link("markdownCodeDelimiter", "Green")
  c.link("markdownBlockquote", "Grey")
  c.link("markdownListMarker", "Red")
  c.link("markdownOrderedListMarker", "Red")
  c.link("markdownRule", "Purple")
  c.link("markdownHeadingRule", "Grey")
  c.link("markdownUrlDelimiter", "Grey")
  c.link("markdownLinkDelimiter", "Grey")
  c.link("markdownLinkTextDelimiter", "Grey")
  c.link("markdownHeadingDelimiter", "Grey")
  c.link("markdownLinkText", "Red")
  c.link("markdownUrlTitleDelimiter", "Green")
  c.link("markdownIdDeclaration", "markdownLinkText")
  c.link("markdownBoldDelimiter", "Grey")
  c.link("markdownId", "Yellow")
  c.hl("mdURL", c.P.blue, c.NONE, { underline = true })
  c.hl("mkdInineURL", c.P.blue, c.NONE, { underline = true })
  c.hl("mkdItalic", c.P.grey, c.NONE, conf.attrib.italic)
  c.link("mkdCodeDelimiter", "Green")
  c.link("mkdBold", "Grey")
  c.hl("mkdLink", c.P.blue, c.NONE, { underline = true })
  c.link("mkdHeading", "Grey")
  c.link("mkdListItem", "Red")
  c.link("mkdRule", "Purple")
  c.link("mkdDelimiter", "Grey")
  c.link("mkdId", "Yellow")
  c.link("texStatement", "Keyword")
  c.link("texSection", "Keyword")
  c.link("texMatcher", "OrangeBold")
  c.link("texOnlyMath", "Grey")
  c.link("texDefName", "Yellow")
  c.link("texNewCmd", "Orange")
  c.link("texCmdName", "BlueBold")
  c.link("texBeginEnd", "Red")
  c.link("texBeginEndName", "Green")
  c.link("texDocType", "Type")
  c.link("texDocZone", "BlueBold")
  c.link("texDocTypeArgs", "Orange")
  c.link("texInputFile", "Green")
  c.link("texFileArg", "Green")
  c.link("texCmd", "Keyword")
  c.link("texCmdPackage", "BlueItalic")
  c.link("texCmdDef", "Red")
  c.link("texDefArgName", "Yellow")
  c.link("texCmdNewcmd", "Red")
  c.link("texCmdClass", "Red")
  c.link("texCmdTitle", "Red")
  c.link("texCmdAuthor", "Red")
  c.link("texCmdEnv", "Red")
  c.link("texCmdPart", "BlueBold")
  c.link("texEnvArgName", "Green")
  c.link("texDelimiter", "PunctDelim")
  c.link("texArg", "String")
end

local M = {}
function M.set()
  _set()
end

return M

