site_name: Subspace Neovim Config
site_dir: /data/mnt/shared/data/silvercircle2.gitlab.io/_site/nvim
site_url: https://subspace.cc/nvim
extra_css:
  - css/fonts/breve-sans.css
  - css/style.css
theme:
  color_mode: dark
  user_color_mode_toggle: true
  name: material
  nav_style: dark
  locale: en
  static_templates:
    - sitemap.html
  include_sidebar: true
  palette:
    - scheme: slate
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.path
    - toc.integrate
    - toc.follow
plugins:
  - glightbox
  - search
  - tags
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: false
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - scripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

